name: CI

on:
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - run: npm install --frozen-lockfile

      - run: npm run build
        env:
          VUE_APP_API_SERVER: ${{ secrets.VUE_APP_API_SERVER }}
          VUE_APP_API_SERVER_LONG_POLLING_TIMEOUT_SEC: ${{ secrets.VUE_APP_API_SERVER_LONG_POLLING_TIMEOUT_SEC }}
          VUE_APP_STRIPE_KEY: ${{ secrets.VUE_APP_STRIPE_KEY }}
          VUE_APP_PRICE_PER_STRGZN_CENTS: ${{ secrets.VUE_APP_PRICE_PER_STRGZN_CENTS }}
          VUE_APP_PRICE_PER_NFT_STRGZNS: ${{ secrets.VUE_APP_PRICE_PER_NFT_STRGZNS }}
          VUE_APP_ACCESS_TOKEN_ASSET_ID: ${{ secrets.VUE_APP_ACCESS_TOKEN_ASSET_ID }}
          VUE_APP_ACCESS_TOKEN_RECV_ACCOUNT: ${{ secrets.VUE_APP_ACCESS_TOKEN_RECV_ACCOUNT }}
          VUE_APP_TYPEFORM_ID: ${{ secrets.VUE_APP_TYPEFORM_ID }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: telescope.merklebot.com
